### ISSUE TITLE
Bad behavior when class docs and __init__ docs are both present

### ISSUE THREAD

**Issue by iconmaster5326** [tox-dev/sphinx-autodoc-typehints#105]
In my `conf.py`, I have an autodoc configuration like the following:

```python3
autoclass_content = "class"
autodoc_default_options = {
    "special-members": True,
    "exclude-members": "...",
}
```

Without these changes to settings, the docstring for `__init__` is ignored, and only the class's docstring is used, intended by Sphinx to refer to `__init__` rather than the class itself. But with these changes, the class and `__init__` both have separate documentation, and constructor parameters, etc. I intend to be in `__init__`'s documentation.

This extension is not aware of this fact. When I have something like:

```python3
class Example:
    """An example class. Attribute documentation, etc. should go here.
    :var y: an example attribute.
    """
    def __init__(self, x: str):
        """Construct a new Example. Parameter, raises, etc. documentation should go here.
        :param x: an example parameter.
        """
```

It produces something like this:
```python3
class Example:
    """An example class. Attribute documentation, etc. should go here.
    :var y: an example attribute.
    :type x: str
    """
    def __init__(self, x: str):
        """Construct a new Example. Parameter, raises, etc. documentation should go here.
        :param x: an example parameter.
        """
```

When it needs to be producing:
```python3
class Example:
    """An example class. Attribute documentation, etc. should go here.
    :var y: an example attribute.
    """
    def __init__(self, x: str):
        """Construct a new Example. Parameter, raises, etc. documentation should go here.
        :param x: an example parameter.
         :type x: str
        """
```

This is especially apparent with `always_document_param_types = True`, where it duplicates parameters from `__init__` into the class's docstring. Not exactly a desirable behavior!

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
