### ISSUE TITLE
Allow customizing formatter

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/sphinx-autodoc-typehints#112]
Before making a PR, I’d like to check if you’d be open to the idea.

Basically, instead of `format_annotation(annotation, fully_qualified=False)`, we’d have

```py
class AnnotationFormatter:
    def __init__(self, *, fully_qualified=False):
        self.fully_qualified = fully_qualified
    def format(self, annotation) -> str:
        ...
```

Also a new config option `typehints_format_cls` where people would have the ability to override formatting:

```py
class CustomFormatter(sat.AnnotationFormatter):
    def format(self, annotation) -> str:
        if isinstance(annotation, MyClass):
            return ...
        return super().format(annotation)

typehints_format_cls = CustomFormatter
```

For backwards compatibility (if desirable), we could define

```py
def format_annotation(annotation, fully_qualified=False):
    return AnnotationFormatter(fully_qualified=fully_qualified).format(annotation)
```

**Comment by flying-sheep** [comment]
Hi @agronholm, your latest release broke our monkeypatching in [scanpydoc.elegant_typehints](https://icb-scanpydoc.readthedocs-hosted.com/en/latest/scanpydoc.elegant_typehints.html), which we need to do because this doesn’t exist.

Can we get this into a release quickly if someone submits a PR?

**Comment by agronholm** [comment]
I'm willing to accept a PR for a customized formatting callback in the configuration. You can make a suggestion and we'll go from there.

**Comment by flying-sheep** [comment]
Which of the two suggestions would you prefer? Class or function?

**Comment by agronholm** [comment]
The function.
