### ISSUE TITLE
NoneType for NamedTuple during process_signature

### ISSUE THREAD

**Issue by sebihoefle** [tox-dev/sphinx-autodoc-typehints#121]
I have the following NamedTuple:
```
from typing import NamedTuple

class SampleNamedTuple(NamedTuple):
    """Sample Named Tuple"""

    attr1: int
    """Attribute"""
```

This NamedTuple causes trouble during output building:

```
Exception occurred:
  File "//anaconda3/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 179, in process_signature
    outer = getattr(outer, clsname)
AttributeError: 'NoneType' object has no attribute 'SampleNamedTuple'
```

Versions:
Python 3.7.3
Sphinx v2.2.1
sphinx-autodoc-typehints 1.10.3

Note, that I did not use the napoleon extension at all, just:
```
extensions = ["sphinx.ext.autodoc", "sphinx_autodoc_typehints"]
```

Are NamedTuples supported or at least expected to be processed without throwing exceptions? 

Related issues:
#42 
#68

**Comment by sebihoefle** [comment]
Alternative definition as a workaround:
```
from typing import NamedTuple

SampleNamedTuple = NamedTuple("SampleNamedTuple", [("attr1", int)])
```

**Comment by ahoereth** [comment]
Still open, just ran into this myself again :( They even reopened a related issue: https://github.com/agronholm/sphinx-autodoc-typehints/issues/68

Can be worked around by using Python 3.7

**Comment by johnberroa** [comment]
For future onlooker, an important distinction: this is using the `Typing.NamedTuple`, not the `collections.namedtuple`. Using the later doesn't work. The former does.

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
