### ISSUE TITLE
Possible way to reduce unresolved forward reference warnings

### ISSUE THREAD

**Issue by rmorshea** [tox-dev/sphinx-autodoc-typehints#128]
# Background

Forward references are pretty problematic when it comes to documenting type hints. For example, the following will cause a warning:

```python
# this_module.py
A = int
B = Callable[..., "A"]
```

```python
# other_module.py
from this_module import B

def func() -> B:
    "The function being documented"""
```

```
WARNING: Cannot resolve forward reference in type annotations of "other_module.func": name 'A' is not defined
```

This occurs because the type hint resolver does not know what the string `"A"` refers to when it has been imported from `this_module` into the `other_module`.

# Possible Solution

The only thing I can think of to resolve this issue is to look at the AST, and determine what has been imported into the namespace and from where it was imported. Given the above example, one could analyze the AST to determine that the type hint `B` was imported from `this_module` and that it ought to resolve the forward reference `A` inside the context of `this_module` instead of the `other_module` (as it does presently).

This approach probably has many complicated edge cases. For example, what happens if a variable named `A` is defined inside the `other_module` and how would you know that the forward reference didn't refer to it? However I think that most of these issue could be solved, and that this approach would alleviate a major pain point.

**Comment by gaborbernat** [comment]
Closing per above.
