### ISSUE TITLE
Use type hints extracted from docstring for native extension

### ISSUE THREAD

**Issue by jfolz** [tox-dev/sphinx-autodoc-typehints#135]
For native code extension modules sphinx autodoc extracts the function signature, including type hints, from the first line of the docstring when `autodoc_docstring_signature` is set.
I dug around pretty deep in the code and as far as I can tell all of the methods used by this extension tap into the `__annotations__` dict, which native functions don't have. Can this extension be configured to use the signature extraction that sphinx provides?
I guess I should add that I'm using napoleon with Google style docstrings, following #15, but writing `:param:`s directly doesn't make any difference.

Below is my current solution (to be put in `conf.py`). It works, but it's exceedingly janky and will probably breaks in many exciting ways in the future.

```python
TYPE_HINTS = {}


# Record type hints
def record_type_hints(app, what, name, obj, options, signature, return_annotation):
    TYPE_HINTS[name] = {}
    if signature is not None:
        for arg in signature.strip('()').split(','):
            k, _, v = arg.partition(':')
            k = k.strip()
            v = v.strip()
            if k and v:
                TYPE_HINTS[name][k] = v
    if return_annotation is not None:
        TYPE_HINTS[name]['return'] = return_annotation
    return signature, return_annotation


# Add recorded type hints to function parameters
def add_type_hints(app, what, name, obj, options, lines,
                   __param_pattern=re.compile(r'^:param ([^:]+):')):
    rtype = False
    for i, line in enumerate(lines):
        m = __param_pattern.search(line)
        if m is not None:
            arg = m.groups(0)[0]
            hint = TYPE_HINTS[name].get(arg)
            if hint:
                lines[i] = line.replace(f':param {arg}:', f':param {hint} {arg}:', 1)
        elif line.startswith(':rtype:'):
            rtype = True
    if not rtype and TYPE_HINTS[name].get('return'):
        lines.append(f':rtype: {TYPE_HINTS[name].get("return")}')


def setup(app):
    app.connect("autodoc-process-signature", record_type_hints)
    app.connect("autodoc-process-docstring", add_type_hints)
```

**Comment by jfolz** [comment]
Is already broken for default values ;)

**Comment by gaborbernat** [comment]
I'd say the path ahead for this would be to support stub files, for which there's another issue.
