### ISSUE TITLE
Removing type hinting from HTML doc doesn't work on cythonised modules

### ISSUE THREAD

**Issue by AdelKS** [tox-dev/sphinx-autodoc-typehints#140]
Hello,

I have been trying to remove the python3 type hinting from the Sphinx generated documentation of my project but to no avail.

aka from the following python function
`def format_unit(value: Union[float, int], unit: str) -> str:`
have the following signature in the HTML documentation:
`def format_unit(value, unit)`

I first tried the [config option of Sphinx's autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints) but it didn't work. then I tried this extension. It works good on python classes but unfortunately not on python cythonised classes.

I don't have enough knowledge to fix the problem myself and PR it, so I made a small git repository with a minimal example where the generated documentation doesn't behave as expected: [it can be found here.](https://github.com/AdelKS/sphinxtypehintproblem)

In the minimal example repository, only Cython is the required. The module can be installed with a `pip install .` then one can do `make html` in the `doc/` and view the generated HTML to see that the type hinting hasn't been removed for `foo.TestClass`.

I hope this is enough information. Otherwise I am here to provide further information and help to the extent of my knowledge.

Thank you for this module and your work.

Adel

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
