### ISSUE TITLE
Fail to process numpy nptyping template types for NDArray[float32]: {TypeError}'type' object is not iterable

### ISSUE THREAD

**Issue by benoitbesson** [tox-dev/sphinx-autodoc-typehints#158]
**The library nptyping** provides hints for numpy types : https://github.com/ramonhagenaars/nptyping

e.g : 
my_array:NDArray[np.int32]

When processing Sphinx doc with these hints, **the code fails**.

The error occurs in sphinx_autodoc_typehints.py::format_annotation.
get_annotation_args() returns **<class 'numpy.int32'> that is not iterable**.

Note : the annotation class __NDArrayMeta does not provide the attribute __args__ as expected as the default case in sphinx_autodoc_typehints::get_annotation_args

**Comment by bskinn** [comment]
Per the ndtyping [README](https://github.com/ramonhagenaars/nptyping), that `NDArray[np.int32]` is really sugar for `NDArray[(typing.Any, ...), np.int32]`, which is converted internally to `NDArray[(typing.Any, ...), Int[32]]`.

![image](https://user-images.githubusercontent.com/11325439/105398844-d3e1c780-5bf0-11eb-9b21-5738ef93271b.png)

**Comment by gaborbernat** [comment]
Closing as per above.
