### ISSUE TITLE
Sphinx cross-references not substituted at deeper levels of nesting for types with nested iterables

### ISSUE THREAD

**Issue by bskinn** [tox-dev/sphinx-autodoc-typehints#162]
I'm looking to use `sphinx-autodoc-typehints` with `nptyping`, and it seems that for types with nested iterables (which will be every use of the `NDArray` type), while the types are correctly resolved out of the annotation syntax at all levels of nesting, the Sphinx cross-reference substitutions are only made at the outermost level of nesting:

For example, with a signature and docstring of:

```
def basis_func(cls, eta: NDArray[(Any, ...), Float], *, n: int) -> NDArray[(Any, ...), Float]:
    """Generate the basis function over `eta` at the given `n`.

    :param eta: Array (multi-dimensional ok) of spatial position values
        over which to calculate basis function values

    :param n: Index value to use in basis function calculation

    """
```

The generated output is:

![image](https://user-images.githubusercontent.com/11325439/105402987-1eb20e00-5bf6-11eb-989a-3fb38d239d8a.png)

----

This is with Python 3.9.1 and:

```
Sphinx==3.4.3
sphinx-autodoc-typehints==1.11.1
nptyping==1.4.0
```

**Comment by gaborbernat** [comment]
Please feel free to put in a PR for this.

**Comment by bskinn** [comment]
Draft PR created in #212.
