### ISSUE TITLE
Incorrect class method type hints using comments

### ISSUE THREAD

**Issue by fmigneault** [tox-dev/sphinx-autodoc-typehints#169]
**Describe the bug**

Type hints documented using `sphinx_autodoc_typehints[type_comments]` seem to behave incorrectly when the hints are under a class method. As shown in the image, the `Str` and `Request` types defined in those cases are placed following `self` instead of their intended argument.

![image](https://user-images.githubusercontent.com/19194484/114063729-e8844200-9866-11eb-8285-255bda9b1bb1.png)

**To Reproduce**

Use any class and define methods type hints using the comment notation.

**Expected behavior**

Hints should be shifted by one argument to the right. Self should not have the hint.

**Comment by gaborbernat** [comment]
A PR for this would be welcome.
