### ISSUE TITLE
Mark tests requiring network

### ISSUE THREAD

**Issue by mcepl** [tox-dev/sphinx-autodoc-typehints#174]
**Is your feature request related to a problem? Please describe.**
All Linux distributions I know about (and perhaps even the non-Linux ones) build their packages in the environment which is isolated from the network.

**Describe the solution you'd like**
[This patch](https://github.com/agronholm/sphinx-autodoc-typehints/files/6365937/no-net-tests.patch.txt) add `network` marker tests which require network, which makes it then trivial to skip all those tests.

**Comment by agronholm** [comment]
Would you make a PR out of this please?

**Comment by mcepl** [comment]
Sorry, I am a maintainer of couple of hundred python-related packages in openSUSE. I just cannot keep git repos for all of them.

**Comment by mcepl** [comment]
Actually, I think I have even better solution in 
[this patch](https://github.com/agronholm/sphinx-autodoc-typehints/files/6366739/python-sphinx-autodoc-typehints-system-object.inv.patch.txt) and then fixing it with one `sed` command.

**Comment by gaborbernat** [comment]
Can you rebase your patch on latest main release?

**Comment by mcepl** [comment]
That’s just laziness.

**Comment by gaborbernat** [comment]
In that case, I'll close this for:
- lack of interest,
- lack of contribution,
