### ISSUE TITLE
Optionally supress return type None of methods or functions

### ISSUE THREAD

**Issue by 1kastner** [tox-dev/sphinx-autodoc-typehints#187]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
At some places, I use type hinting to express that a function or method does not return anything (`def x(...) -> None`). This helps me during development, but for the generated documentation it is sometimes overly expressive.
Thus, I'd like to have the option to supress this type hint.

**Describe alternatives you've considered**
Just keep it as it is.

**Additional context**
It will be added if required later in the discussion.

**Comment by gaborbernat** [comment]
I'd say this is out of scope for this project. We purposefully want to show all type annotations and not make parts of it optional.
