### ISSUE TITLE
New option: use short name for my own module and fully qualified names for foreign modules

### ISSUE THREAD

**Issue by 1kastner** [tox-dev/sphinx-autodoc-typehints#193]
I want to document a module and repeatedly reading the name of the documented module name is tedious. That is why I do not want fully qualified names of my module all over the documentation. At the same time, I import data types from other Python standard libraries, such as `datetime.datetime`, `datetime.time`, etc. Here, I believe a fully qualified name is extremly helpful for the reader to understand that this data type comes from a module the reader already knows (or should know).

My first idea is to add a new configuration variable that keeps a collection (list, set, or similar) of modules that should keep their fully qualified names.

```python

typehints_fully_qualified = False
typehints_fully_qualified_modules = {datetime, itertools}

```

I later ignore these modules anyway, i.e. they are not part of the documentation and no links are set up to the official Python documentation. 

From my first inspection, a few changes at https://github.com/tox-dev/sphinx-autodoc-typehints/blob/main/src/sphinx_autodoc_typehints/__init__.py#L121 should be sufficient but of course there might be edge cases.

Would such a pull request be welcomed at this repository? Do you believe this idea can be fruitful for others as well?

**Comment by gaborbernat** [comment]
> I want to document a module and repeatedly reading the name of the documented module name is tedious.

Can you provide some examples of this? I don't believe we display the fully qualified path always, only the reference is so :thinking: so some reproducible showing the issue would help me understand what you're looking for.

**Comment by 1kastner** [comment]
At https://conflowgen.readthedocs.io/en/latest/api.html#conflowgen.ContainerFlowGenerationManager.set_properties you can see e.g. the following:

![grafik](https://user-images.githubusercontent.com/5236165/148135461-d23a92b4-8fec-415d-88c9-421710c4261e.png)

But I would like to have a preceding `datetime.` there.

However, I want this to stay exactly the way it is:

![grafik](https://user-images.githubusercontent.com/5236165/148135561-743c4002-2439-4f48-ac9a-ce3dd1477780.png)

No preceding module name for my own module documentation, but for the others.

Could I clarify your request?

**Comment by gaborbernat** [comment]
If the link is a reference that points the user to the right direction why do you want the fully qualified name for datetime? I'd find it harder to read it that way 🤔

**Comment by 1kastner** [comment]
For datetime there is no link pointing anywhere. And I believe people would not be sure whether the date I expect here is my own implementation of a date or the implementation of the standard lib they already know.

**Comment by gaborbernat** [comment]
Why wouldn't Bea link? Aren't you using intersphinx to add them in?

**Comment by 1kastner** [comment]
Well, I did not see the necessity until now.

**Comment by gaborbernat** [comment]
IMHO you should favour links over more verbose doc, so as there's an alternative solution I'll decline this feature request. Having a link is a more robust way to specify what object you're referring to.

**Comment by 1kastner** [comment]
I am sorry to hear that but I can understand that not every idea can be included in such a project. Thanks for the discussion anyway!
