### ISSUE TITLE
config.fully_qualified doesn’t exist

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/sphinx-autodoc-typehints#203]
It’s `typehints_fully_qualified`, right?

https://github.com/tox-dev/sphinx-autodoc-typehints/blob/87759d40973921eb69dc3202cac12077cbf9f39b/src/sphinx_autodoc_typehints/__init__.py#L124

**Comment by gaborbernat** [comment]
releasing via https://github.com/tox-dev/sphinx-autodoc-typehints/actions/runs/1677293169
