### ISSUE TITLE
Sphinx 3 is no longer supported

### ISSUE THREAD

**Issue by r-bird** [tox-dev/sphinx-autodoc-typehints#205]
For some reason, the metadata of the [wheel on PyPI](https://pypi.org/project/sphinx-autodoc-typehints/1.14.0/#files) for the release 1.14.0 contains this line:

```
Requires-Dist: Sphinx (>=4)
```

So from this version on Sphinx 3 is no longer supported. 

I don't see how this constraint was introduced (see [diff](https://github.com/tox-dev/sphinx-autodoc-typehints/compare/1.13.1...1.14.0)), but it breaks all of our pipelines that depend on Sphinx 3.

This should either be reversed or a mayor version change should be applied (making the `sphinx-autodoc-typehints` package version `2.0.0`), because this is a breaking change for everyone relying on Sphinx 3.

**Comment by gaborbernat** [comment]
> For some reason, the metadata of the [wheel on PyPI](https://pypi.org/project/sphinx-autodoc-typehints/1.14.0/#files) for the release 1.14.0 contains this line:
> 
> ```
> Requires-Dist: Sphinx (>=4)
> ```
> 
> So from this version on Sphinx 3 is no longer supported.

That is the intention here and works as expected.


> I don't see how this constraint was introduced (see [diff](https://github.com/tox-dev/sphinx-autodoc-typehints/compare/1.13.1...1.14.0)), but it breaks all of our pipelines that depend on Sphinx 3.

https://github.com/tox-dev/sphinx-autodoc-typehints/commit/ab3005aa9cd284185784f0f7ba9d267a0a6df9f0 Sphinx 3 is no longer supported. `pip>9` or later should automatically download the latest compatible version, which on sphinx version 3 is 1.13.1. If you're using an older pip should manually pin. 

> This should either be reversed or a mayor version change should be applied (making the `sphinx-autodoc-typehints` package version `2.0.0`), because this is a breaking change for everyone relying on Sphinx 3.

Only for people having really-really old pip.

**Comment by r-bird** [comment]
> `pip>9` or later should automatically download the latest compatible version, which on sphinx version 3 is 1.13.0. If you're using an older pip should manually pin.

I am using pip 21.3.1 on Python 3.9.

pip is really bad in resolving sub-dependencies. You cannot rely on it, as soon as two packages are depending on the same package.

**Comment by gaborbernat** [comment]
I strongly disagree. If you found a bug please open a reproducible issue to pip. In my experience pip works very well, and with the dependency resolver even for transitive dependencies.
