### ISSUE TITLE
Playing nicely with `napoleon_use_rtype`

### ISSUE THREAD

**Issue by SimonHeybrock** [tox-dev/sphinx-autodoc-typehints#217]
Hi,
Napoleon provides the [napoleon_use_rtype](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#confval-napoleon_use_rtype) option, which can be set to `False`, such that the return type is documented "inline" with the "Returns" section, rather than creating a separate section for it.

However, this extension ignores this (or any presence of a type documented in the `:returns:` directive) and creates an `:rtype:` directive. This may lead to duplicate rendering of the return types.

I have a small fix for this. It is adding about 5 lines of code, and a new option named `typehints_use_rtype`, which can be used in conjunction with `napoleon_use_rtype` (or hand written `:return:` directives of similar format).

If you think this is something you would like to include in this extension I am happy to open a PR. Please let me know.

Simon

**Comment by gaborbernat** [comment]
Sure, please open a PR and we can discuss design 👍
