### ISSUE TITLE
 Documenting static argument & return types of numba-JIT-compiled functions?

### ISSUE THREAD

**Issue by s-m-e** [tox-dev/sphinx-autodoc-typehints#219]
I am heavily using `sphinx`, `autodoc` and `sphinx-autodoc-typehints` to document code. I am also using `numba` to JIT-compile (some) functions. I typically statically type my JIT-compiled functions via `numba`’s `jit` and `njit` decorators instead of using Python type annotations (because `numba` does not understand them). I was wondering if there was a tool or plugin for `sphinx` similar to `sphinx-autodoc-typehints` that would be able to pick up the types specified via `numba`. Or `sphinx-autodoc-typehints` perhaps supports it and I overlooked it?

---

Regular Python annotation:

```python
def foo(bar: float) -> float:
    return bar ** 2
```

Statically typed, numba-JIT-compiled function:

```python
@numba.njit('f8(f8)')
def foo(bar):
    return bar ** 2
```

**Comment by gaborbernat** [comment]
AFAIK this has not been created yet and we don't support it yet. I'm personally not sure it belongs to this project though 🤔

**Comment by gaborbernat** [comment]
Closing as there doesn't seem to be a wide interest for it just yet.
