### ISSUE TITLE
Recursion errors with some recursive types 

### ISSUE THREAD

**Issue by cpsievert** [tox-dev/sphinx-autodoc-typehints#223]
It appears #91 has been reintroduced by the 1.6.0 release. That is, a recursive type definition like

```py
TreeType = typing.Dict[str, typing.Union['TreeType', typing.List['TreeType']]]
```

causes documentation generation to fail with the following recursion error.

```py
Extension error (sphinx_autodoc_typehints):
Handler <function process_docstring at 0x7ff706291310> for event 'autodoc-process-docstring' threw an exception (exception: maximum recursion depth exceeded)
```

**Comment by gaborbernat** [comment]
Feel free to put in an PR to address the problem 👍

**Comment by hmc-cs-mdrissi** [comment]
I've hit this issue and debugging the cycle comes from [here](https://github.com/tox-dev/sphinx-autodoc-typehints/blob/7ee38919ba491d79918b1224ddcf0460db467514/src/sphinx_autodoc_typehints/__init__.py#L120),'

```python
    if isinstance(annotation, ForwardRef):
        value = _resolve_forward_ref(annotation, config)
        return format_annotation(value, config)
```
The logic when it resolves the type will create a new forward reference to that type and just repeated resolve/format it. The main question is why do we even resolve the type in first place? If it's a forward reference why not use string value directly? Even when from future import annotations is present, get_type_hints call from before this will lead to some resolution.


TreeType = typing.Dict[str, typing.Union['TreeType', typing.List['TreeType']]]

def foo(x: 'TreeType'):
  ...

what should format_annotation return here? Easiest solution is to not resolve the type and to keep original string contents as formatting. I think that is also more readable then resolving it here. If that's fine the simple fix would be just do,

```python
    if isinstance(annotation, ForwardRef):
        return annotation.__forward_code__
```

If we do need to resolve it then we need recursion detection for aliases. In simple case you can just check for name appearing in type after doing 1 iteration of resolving, but in general you may have something like,

A = X | Y
X = B
Y = A

or many more levels before recursion happens. The correct logic would be build a graph of relationships between forward refs encountered and then do cycle check on it. That's doable but I'm unsure it's worth complexity vs simple solution of don't resolve here.

**Comment by hmc-cs-mdrissi** [comment]
@gaborbernat poking on this. Which approach would you want? A simple approach using `__forward_arg__ ` or a more complex approach checking if a type alias is recursive (including mutual recursion/several nested levels to check). And either way what is desired output?

My preference is simple approach, but I'm willing to work on complex way if needed.

**Comment by rhaps0dy** [comment]
I think you should do the `__forward_arg__` approach. Thank you for the solution @hmc-cs-mdrissi , I'm going to put this on my fork now.

**Comment by gaborbernat** [comment]
Go ahead for a simple approach for now in a PR 👌
