### ISSUE TITLE
build fails with functools.singledispatchmethod using sphinx 5

### ISSUE THREAD

**Issue by elfjes** [tox-dev/sphinx-autodoc-typehints#233]
When using `functools.singledispatchmethod`, sphinx-autodoc-typehints breaks the build process with the following message

`WARNING: error while formatting signature for foo.Foo.bar: Handler <function process_signature at 0x7f477ba58790> for event 'autodoc-process-signature' threw an exception (exception: 'NoneType' object has no attribute 'endswith')`

example:

foo.py
```python3
import functools


class Foo:
    @functools.singledispatchmethod
    def bar(self, a):
        pass

    @bar.register
    def dispatch(self, a: int):
        pass
```

foo.rst
```
foo module
==========

.. automodule:: foo
   :members:
   :undoc-members:
   :show-inheritance:
```

```
Sphinx                        5.0.1
sphinx-autodoc-typehints      1.18.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
```

without `sphinx-autodoc-typehints` this compiles just fine

**Comment by gaborbernat** [comment]
A PR addressing this is welcome. I personally don't use single dispatch much 👍 and I don't believe we have a test for it.

**Comment by elfjes** [comment]
While troubleshooting, this appeared to be a sphinx autodoc issue:
https://github.com/sphinx-doc/sphinx/issues/10529
