### ISSUE TITLE
1.19.3: _get_sphinx_line_keyword_and_argument: IndexError: list index out of range

### ISSUE THREAD

**Issue by ewjoachim** [tox-dev/sphinx-autodoc-typehints#259]
Hello,

My CI just broke after building with the new 1.19.3. I haven't investigated yet, but it breaks inside sphinx-autodoc-typehints hours after a new release, so that seems highly suspicious :) I'll investigate at some point, but in the meantime, if the following error log and project help you find and squash the bug, I'll be happy to leave you to it :)

Project: https://github.com/procrastinate-org/procrastinate/pull/684
CI Failure: https://readthedocs.org/projects/procrastinate/builds/18176516/

**Comment by ascillitoe** [comment]
We are also experiencing the same failure in our CI:

https://github.com/SeldonIO/alibi-detect/actions/runs/3132027851/jobs/5088241046

**Comment by haiiliin** [comment]
I also encountered this problem:
https://github.com/haiiliin/abqpy/actions/runs/3132489988/jobs/5084889072

**Comment by damiengermonville** [comment]
Hi,

Same here, quickly investigated to find that (in my case) the `.. code-block::` sections are involved : 

```
In [1]: from sphinx_autodoc_typehints import _get_sphinx_line_keyword_and_argument

In [2]: _get_sphinx_line_keyword_and_argument(".. code-block:: python")
param_line_without_description ['.. code-block', '', ' python']
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-eed0d838ba14> in <module>
----> 1 _get_sphinx_line_keyword_and_argument(".. code-block:: python")

[REDACTED]/venv/lib/python3.9/site-packages/sphinx_autodoc_typehints/__init__.py in _get_sphinx_line_keyword_and_argument(line)
    529     print("param_line_without_description", param_line_without_description)  # added debug print
    530     if len(split_directive_and_name) != 2:
--> 531         return (split_directive_and_name[0], None)
    532 
    533     return tuple(split_directive_and_name)  # type: ignore

IndexError: list index out of range
```

**Mitigation** : downgraded to sphinx-autodoc-typehints==1.19.2 fixed the issue (for me).

**Comment by ewjoachim** [comment]
Haha, that was fast <3 I see 1.19.4 is out too !

You're awesome, thank you !

**Comment by ewjoachim** [comment]
(I've sponsored you a coffee/beer/beverage of your choice)
