### ISSUE TITLE
Add example of sphinx doc to README

### ISSUE THREAD

**Issue by ketozhang** [tox-dev/sphinx-autodoc-typehints#266]
Currently this extension has no preview of what it would look like in the repo README.

For some reason the homepage entry on PyPI points to https://pyproject-api.readthedocs.io/en/latest/ , which does have a valid output of this extension.

**Comment by gaborbernat** [comment]
It's because of this - https://github.com/tox-dev/sphinx-autodoc-typehints/blob/main/pyproject.toml#L12 
we should change that to become the URI for this repo, and in the readme at top add a link to that as example 👍  PR welcome

**Comment by ketozhang** [comment]
PR'd

> we should change that to become the URI for this repo

That would be helpful, thanks!
