### ISSUE TITLE
autodoc_type_aliases 

### ISSUE THREAD

**Issue by patrick-nicodemus** [tox-dev/sphinx-autodoc-typehints#284]
As of version 3.3, Sphinx provides the functionality for a dictionary called `autodoc_type_aliases` in which the user can explicitly put type aliases that they do not want the autodoc to unravel in the documentation.

https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_type_aliases

It would be good if this plugin would also support this feature or provide an equivalent! I was trying to understand why adding values to this dictionary was not having the desired effect as described in the documentation above and spent a while trying to debug this before I realized that this package is either interfering with that functionality or does not replace it.

This is closely related to #132, however at the current time even when using the syntax `MyType : TypeAlias = Tuple[int,str]` of https://www.python.org/dev/peps/pep-0613/ this appears not to solve the problem.

**Comment by gaborbernat** [comment]
PR welcome 😊

**Comment by tikuma-lsuhsc** [comment]
@patrick-nicodemus - I just pushed the PR to address this. The latest release (2.2) has it merged. So, please try it out. It should honor the `autodoc_type_aliases` config now.

**Comment by hoodmane** [comment]
Closing as completed by #459.
