### ISSUE TITLE
Release tag for 1.23.4 is wrong. It should be 1.21.4

### ISSUE THREAD

**Issue by HuangJunye** [tox-dev/sphinx-autodoc-typehints#301]
Release tag for 1.23.4 is wrong. It should be 1.21.4.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/7631333/213143852-1864c3b3-0ab7-4e8d-b587-26bab945f023.png">

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/sphinx-autodoc-typehints/releases/tag/1.21.4

**Comment by clement-uspace** [comment]
On conda-forge the release tag 1.23.4 is still there, and is the version being installed when updating (since it's a higher version number than the new releases). 
On that note, I've also noticed that there are no releases after 1.21.3 on conda-forge

**Comment by gaborbernat** [comment]
It's not us maintaining that, so you'll have to fill an issue with them.
