### ISSUE TITLE
Unexpected output when class attribute and constructor arg have same name (napoleon bug)

### ISSUE THREAD

**Issue by hoodmane** [tox-dev/sphinx-autodoc-typehints#308]
This is an upstream bug: https://github.com/sphinx-doc/sphinx/pull/11143

Suppose we have the following class:
```py
class Example:
    """
    A Class

    Parameters
    ----------
    blah:
        Description of parameter blah
    """
    def __init__(self, blah: CodeType):
        pass

    blah: ModuleType
```

We get the following output (just the parameters):
```
   Parameters:
      **blah** (*module*) -- Description of parameter blah
```
Expected output:
```
   Parameters:
      **blah** ("CodeType") -- Description of parameter blah
```
If you want I can provide a monkey patch that implements my fix in https://github.com/sphinx-doc/sphinx/pull/11143 on existing versions of sphinx. I'm not sure how far we want to go in patching with upstream bugs.

**Comment by gaborbernat** [comment]
Unless upstream rejects the PR I see no reason to do it here 🤔

**Comment by hoodmane** [comment]
Well the current behavior is quite clearly wrong so I sure hope they'll accept it. In my experience they are a bit slow about reviewing things. I'll open a PR.

Actually, one thing worth noting is that if we got the upstream change in, we would end up with the parameter type rendered as `*code*` (and no link if we use intersphinx/html) rather than `"CodeType"` (and a link). For some reason, Napoleon will fetch parameter types for class constructor args but not for parameters or function / method args. I think we might just want to disable this upstream parameter fetching.

In an ideal world, it would emit a `napoleon-render-type` event called with the object to produce a text representative of the object.

**Comment by caffeinepills** [comment]
This broke Google style annotations marked as `Attributes:` from showing types in class header docstrings. (`napoleon_attr_annotations = True`)

For those who ran into this you will have to unpatch the patch:
```py
import sphinx_autodoc_typehints
def _revert_patch():
    pass

sphinx_autodoc_typehints.patches._patch_google_docstring_lookup_annotation = _revert_patch
```

Unfortunately it doesn't apply the same style to the types without some overriding of `GoogleDocstring._parse_attributes_section`, but atleast you can get your types back into the header.
