### ISSUE TITLE
Sphinx extension loading failed (cannot import name '__version__')

### ISSUE THREAD

**Issue by bringhurst** [tox-dev/sphinx-autodoc-typehints#327]
I'm running into the following problem when trying to use newer versions of sphinx-autodoc-typehints.

I've narrowed it down as far as:

```
works fine = sphinx-autodoc-typehints 1.18.1
errors out = sphinx-autodoc-typehints 1.22
```

The error I'm seeing is:

```
   > Sphinx docs generation failed:
     Running Sphinx v5.3.0
     STDERR:

     Extension error:
     Could not import extension sphinx_autodoc_typehints (exception: cannot import name '__version__' from 'sphinx_autodoc_typehints.version' (/<snip>/lib/python3.10/site-packages/sphinx_autodoc_typehints/version.py))
```

The contents of `version.py` are:

```
$ cat version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.22'
version_tuple = (1, 22)
$
```

It looks like a similar report (with additional details related to isolated builds) can also be found at:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269686

**Comment by bringhurst** [comment]
I've attempted to use the latest versions of Sphinx and setuptools-scm at the time of this writing, and the error persists.

**Comment by gaborbernat** [comment]
You installed the project in a non supported way, and hatch-vcs could not generate the version information.

**Comment by bringhurst** [comment]
I've narrowed down the problem to:

working = 1.19.5
broken = 1.20.0

As @gaborbernat mentioned, that means this issue is likely caused by the migration from setuptools to hatchling (which uses setuptools-scm via hatch-vcs) in https://github.com/tox-dev/sphinx-autodoc-typehints/commit/ccc75d244d0f4452048f80fc73e39a34a4eefc00

**Comment by gaborbernat** [comment]
This is not a problem for this project but should be a comment for upstream repackaging sources.

**Comment by bringhurst** [comment]
Just a bit more info on what happened here for anyone reading this in the future:

Before the change at https://github.com/tox-dev/sphinx-autodoc-typehints/commit/ccc75d244d0f4452048f80fc73e39a34a4eefc00, setuptools-scm was pinned at `>=7.0.5`.

However, the migration to hatchling downgraded the version of setuptools-scm to `>=6.4.0` (transitive import via hatch-vcs).

This resulted in the change of `TEMPLATES` used to write out the `version.py` within setuptools-scm, which changed the format of the version.py file. Search for `TEMPLATES` in this diff to see details:

https://github.com/pypa/setuptools_scm/compare/v6.4.0...v7.0.5#diff-bdefa0298003efada7c465428643cc6d9c129168afb3eb5c551b40fcc77feac1L35

After a bit of digging, it looks like this issue has already been mentioned in hatch-vcs over at: https://github.com/ofek/hatch-vcs/issues/25
