### ISSUE TITLE
Inconsistent behavior of fully qualified type hints.

### ISSUE THREAD

**Issue by nikfilippas** [tox-dev/sphinx-autodoc-typehints#351]
In `conf.py` I have set `typehints_fully_qualified = False`.
However, while most type hints adhere to this, there are some cases where they appear fully qualified for no apparent reason.

For example
```python
def mass_translator(
        *,
        mass_in: Union[str, MassDef],
        mass_out: Union[str, MassDef],
        concentration: Union[str, Concentration]
) -> Callable[[Cosmology, Union[Real, NDArray], Real],
              Union[Real, NDArray]]:
```
gets interpreted as
![Screenshot from 2023-04-28 11-22-04](https://user-images.githubusercontent.com/22447385/235095068-865c84b1-b133-487e-a061-cc11172a812b.png)

while
```python
def convert_concentration(
        cosmo: Cosmology,
        *,
        c_old: Union[Real, NDArray[Real]],
        Delta_old: Real,
        Delta_new: Real
) -> Union[float, NDArray[float]]:
```
looks alright
![Screenshot from 2023-04-28 11-26-31](https://user-images.githubusercontent.com/22447385/235096110-7b0f0f3e-9b16-4307-9c15-89c24663fea0.png)

It also doesn't work well at all with `numpy.typing.ArrayLike`, as it always fully qualifies it:
```python
-> ArrayLike
```
becomes
![Screenshot from 2023-04-28 11-28-30](https://user-images.githubusercontent.com/22447385/235096690-59fd56b6-4ace-4afc-b523-9b5beddd83ee.png)

This is the rest of the config for `autodoc` and `autodoc_typehints`:
```python
# Additional `autodoc` options.
autodoc_default_options = {
    "member-order": "bysource",
    "show-inheritance": True,
    "inherited-members": True,
    "special-members": "__call__",
}

# Options for `sphnix_autodoc_typehints`.
typehints_fully_qualified = False
typehints_defaults = "braces"
typehints_document_rtype = False
typehints_use_signature_return = True
```
I use Sphinx 6.2.1 and Python 3.11 on Ubuntu 22.04 LTS.
`sphinx_autodoc_typehints.__version__ = '1.21.8'`.

**Comment by nikfilippas** [comment]
@gaborbernat quick question regarding `ArrayLike`: could you verify that you can reproduce the problem, or am I doing something wrong with the options I am passing to the extension?

**Comment by gaborbernat** [comment]
Can't help you, if you find the problem, PR welcome.

**Comment by gaborbernat** [comment]
Seems stalled.

**Comment by nikfilippas** [comment]
FYI this is still an issue, it isn't completed. I have provided all the info needed to reproduce it, but let me know if I can provide you with anything else too.

**Comment by nikfilippas** [comment]
I don't know what is happening under the hood, so unfortunately I can't contribute with a PR. I opened an issue because I feel like this is a bug to do with the repo.
If the Issue log here is only meant to represent a to-do list feel free to close.

**Comment by gaborbernat** [comment]
It's a TODO list for the community; I'm just the maintainer here, not the developer in residence 😊 we can keep it open if you think we have all the info you wanted.

**Comment by nikfilippas** [comment]
Yes, I think all the info needed to reproduce is provided.

PS: I know it's a community project, and that's why I never asked that someone in particular solves it. I only raised the fyi because you closed it as "completed" without the bug having actually been fixed.
