### ISSUE TITLE
Relax Sphinx version requirement

### ISSUE THREAD

**Issue by jooola** [tox-dev/sphinx-autodoc-typehints#376]
The required sphinx version for this extension is >=7.0.1 https://github.com/tox-dev/sphinx-autodoc-typehints/blob/ae448e21c21faf6aedeedb8244c9a5c38f25db71/pyproject.toml#L41

We use the sphinx readthedocs theme, and they do not support sphinx 7 yet https://github.com/readthedocs/sphinx_rtd_theme/issues/1463 and I propose to relax the sphinx version requirement to allow for versions `>=6,<8`.

According to this commit a021cc8b39b10e145fb1f5cc651baf411f746482, the bumped happened in the middle of a larger change without much consideration, is that correct ?

**Comment by gaborbernat** [comment]
IMHO this is a problem for the theme, not us.

**Comment by gaborbernat** [comment]
> a larger change without much consideration

For what's worth it's done because that's the only version we test again in the CI, so we only know it will work with the latest version.
