### ISSUE TITLE
Reexported classes aren’t linked

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/sphinx-autodoc-typehints#38]
For example:

```py
def foo(m: scipy.sparse.spmatrix):
   pass
```

Will not get a linked parameter type, since the qualname is <code>scipy.sparse.*base*.spmatrix</code>, and `` :class:`~scipy.sparse.spmatrix` `` will therefore point nowhere in the docs index.

**Comment by agronholm** [comment]
I'm aware of this, but how do you expect me to fix this?

**Comment by flying-sheep** [comment]
Good question. I’d say, that depends on the reaction to sphinx-doc/sphinx#4826. If they do this quickly, we don’t need to do anything. but if they don’t, maybe we’ll come up with an idea…

Naively, all module hierarchies in the intersphinx mappings could be walked, and a graph constructed for the different locations objects reside in (e.g. walking `scipy` will reveal that both `scipy.sparse` and `scipy.sparse.base` contain the same class). Then we could search all alternative locations in the mapping, and create a substitution dictionary from non-existing doc entries to existing ones. (In our example it would then contain `{…, 'scipy.sparse.base.spmatrix': 'scipy.sparse.spmatrix', …}`)

**Comment by goerz** [comment]
In the absence of https://github.com/sphinx-doc/sphinx/issues/4826 being solved, maybe the `autodoc-typehints` plugin could support an option in `conf.py` that maps qualnames to canonical names. For example, in reaction to

    WARNING: py:class reference target not found: qutip.qobj.Qobj

in https://readthedocs.org/projects/weylchamber/builds/8294327/, I could manually define `autodoc_typehints_name_map = {'qutip.qobj.Qobj': 'qutip.Qobj'}` in `conf.py`. It's a crude workaround, but it's better than nothing. To be honest, problems like https://github.com/sphinx-doc/sphinx/issues/4826 in the basic tooling is an indication to me that type-annotations are nowhere near ready for prime-time.

**Comment by flying-sheep** [comment]
As a crude hack to do this in your own project now, you can put the following in your <samp>conf.py</samp>

```py
import sphinx_autodoc_typehints

qualname_overrides = {
    'anndata.base.AnnData': 'anndata.AnnData',
    'scipy.sparse.base.spmatrix': 'scipy.sparse.spmatrix',
    'scipy.sparse.csr.csr_matrix': 'scipy.sparse.csr_matrix',
    'scipy.sparse.csc.csc_matrix': 'scipy.sparse.csc_matrix',
}

fa_orig = sphinx_autodoc_typehints.format_annotation
def format_annotation(annotation):
    if inspect.isclass(annotation):
        full_name = f'{annotation.__module__}.{annotation.__qualname__}'
        override = qualname_overrides.get(full_name)
        if override is not None:
            return f':py:class:`~{override}`'
    return fa_orig(annotation)
sphinx_autodoc_typehints.format_annotation = format_annotation
```

**Comment by agronholm** [comment]
That problem has nothing to do with type annotations. I was struggling with it way before type annotations were introduced to Python.

**Comment by flying-sheep** [comment]
Of course, the problem surfaces whenever you programmatically access a reexported class’ qualified name and expect to link to its docs. This project just happens to work that way and therefore exposes the problem.

**Comment by agronholm** [comment]
One possible solution is to do what trio does: change the qualified name of the classes and functions: https://github.com/python-trio/trio/blob/master/trio/__init__.py

**Comment by flying-sheep** [comment]
Hmm, that only works if we know which the canonical module is right?

Or do you mean that the original modules could do that? Then we have to convince them to do it.

Of course we could also do what I said in https://github.com/agronholm/sphinx-autodoc-typehints/issues/38#issuecomment-379756476. Or we could just try to import all the names in `intersphinx_mapping` and whenever we encounter a class in `format_annotation`, we could try to find it in the list of canonical names:

```py
canonical_paths = {}
for url, altfile in intersphinx_mapping.values():
    inv = fetch_inventory(..., url, altfile)
    for sect_name, section in inv.values():
        if not sect_name.startswith('py:'): continue
        for item_path in section.keys():
            o = try_import(item_path)
            if o is not None:
                canonical_paths[id(o)] = item_path

def format_annotation(annotation):
    ...
    if inspect.isclass(annotation):
        full_name = canonical_paths.get(
            id(annotation),
            f'{annotation.__module__}.{annotation.__qualname__}',
        )
        ...
    ...
```

**Comment by goerz** [comment]
That's pretty much exactly what I had in mind! Thanks!


On 19 Dec 2018 00:55 -0800, Philipp A. wrote:
> As a crude hack to do this in your own project now, you can put the
> following in your conf.py> import sphinx_autodoc_typehints  qualname_overrides = {
> 'anndata.base.AnnData': 'anndata.AnnData',
> 'scipy.sparse.base.spmatrix': 'scipy.sparse.spmatrix',
> 'scipy.sparse.csr.csr_matrix': 'scipy.sparse.csr_matrix',
> 'scipy.sparse.csc.csc_matrix': 'scipy.sparse.csc_matrix', }  fa_orig =
> sphinx_autodoc_typehints.format_annotation def
> format_annotation(annotation):  if inspect.isclass(annotation):
> full_name = f'{annotation.__module__}.{annotation.__qualname__}'
> override = qualname_overrides.get(full_name)  if override is not None:
> return f':py:class:`~{override}`'  return fa_orig(annotation)
> sphinx_autodoc_typehints.format_annotation = format_annotation> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/agronholm/sphinx-autodoc-typehints/issues/38#issuecomment-448517805

**Comment by goerz** [comment]
> That problem has nothing to do with type annotations. I was struggling with it way before type annotations were introduced to Python.
I suppose you're right.

It's just that when I do the documentation manually, I will write

    Args:
        m (scipy.sparse.spmatrix): sparse matrix parameter

in my docstring, somehow having figured out that that's what generates a working link the rendered Sphinx docs. So you mean that before type annotations, the problem was manually figuring out the canonical name for the linking, right?

With type annotations, it seems I just don't have that option. There, I will have

    from scipy.sparse import spmatrix  # or, `from scipy.sparse.base import spmatrix`

    def f(m: spmatrix):
        """My function

        Args:
            m: sparse matrix parameter
        """
        pass

with no control over what link is generated. In *theory*, the type annotated version is nicer, because those manual type specifications in the docstring tend to take up a lot of space. But of course, the point is moot unless Sphinx links correctly by figuring out the canonical name automatically.

I actually don't think I fully understand how scipy manages to define `spmatrix` in `scipy.sparse.base`, but the canonical link location is in `scipy.sparse`, where it is re-exported.

I always thought it would be really nice if Sphinx *in general* allowed me to specify the type with any importable specification, and it would link correctly. In my own projects, I generally have classes defined in deep submodules, but they are always re-exported in the main module. It would be much nicer if in all of my docstrings I could write

    Args:
        a (mypkg.mycls): a parameter of type :class:`~mypkg.mycls`

instead of

    Args:
        a (mypkg.sub1.sub2.mycls): a parameter of type :class:`~mypkg.sub1.sub2.mycls`

and the link would still go to `mypkg.sub1.sub2.mycls`. But I digress...

**Comment by goerz** [comment]
I suppose that's more or less what https://github.com/sphinx-doc/sphinx/issues/4826 is all about

**Comment by agronholm** [comment]
I will try to find a workaround. I too have significant problems with this in my own projects.

**Comment by flying-sheep** [comment]
@agronholm: what do you think about the solution outlined at the bottom of https://github.com/agronholm/sphinx-autodoc-typehints/issues/38#issuecomment-448552479?

**Comment by agronholm** [comment]
I think it would be better to just add a hook for a callable that looks up the canonical path. Or did I miss something?

**Comment by flying-sheep** [comment]
My solution would work automatically and without user interaction.

**Comment by agronholm** [comment]
> My solution would work automatically and without user interaction.

Could you explain how it works? Due to the pseudocode nature it's not that easy to follow.

**Comment by flying-sheep** [comment]
Yeah, I’m also pleased with the idea. And you got it right, except for

> a map from the actual object (via its id) to the canonical reference-URL

It’s a map from the object ID (correct) to the object *path* (`f'{o.__module__}.{o.__qualname__}'`), not an URL.

**Comment by agronholm** [comment]
I have not yet found any way to access the inventory from the hooks, but if that were possible, I could check if the object exists and if not, check higher levels for an object with the same type and name which would fix most reexports.

**Comment by flying-sheep** [comment]
Of course it’s possible:

- `env.intersphinx_inventory` contains `{'py:func': {'qual.name': (mod.name, version, url, title), ...}, ...}`
- `env.intersphinx_named_inventory` contains `dict(mapping_name={'py:func': {...}, ...}, ...)`

Actually astropy [has code](https://git-cral.univ-lyon1.fr/MUSE/mpdaf/blob/23d52ba059fe76df5e1655542b17a28a7137cf20/doc/ext/smart_resolver.py) that does it.

**Comment by agronholm** [comment]
Thanks, I will look at this later and see if it can help to fix the issue.

**Comment by agronholm** [comment]
But does that exist even when intersphinx is not enabled, and does it contain the inventory for the current project?

**Comment by flying-sheep** [comment]
No and no. They manually create an inventory for the current project (`env.class_name_mapping`) from the `autodoc-process-docstring` handler and consult both the intersphinx inventory and that one in the `missing-reference` handler.

Idk if there’s separate passes we could use instead of `missing-reference` to create the correct links in the first place.

**Comment by agronholm** [comment]
I think I'm still missing a piece of the picture. How does the `missing-reference` hook help us figure out the correct reference?

**Comment by agronholm** [comment]
Ok, I think I might get it now – the `autodoc-process-docstring` handler gets both the API name and the actual object, and this could be used to fix the problem. I'll post an update once I've experimented a bit.

**Comment by agronholm** [comment]
Ok, I think I'm making some headway with this. Next I need to construct two tests:

1. A reference to a class in the current project re-exported to the top level package
2. A reference to a class from the standard library that has been re-exported to another package (e.g. `concurrent.futures.ThreadPoolExecutor`)

**Comment by flying-sheep** [comment]
Hi, if you’re stuck, how about publishing the branch with your partial work so one of us can finish it?

**Comment by agronholm** [comment]
I had totally forgotten about this. I'll see if I can find the code.

**Comment by agronholm** [comment]
I can't find anything relevant in local branches or the git shelf. Seems like I didn't get anywhere yet regarding code updates.

**Comment by eric-wieser** [comment]
> One possible solution is to do what trio does: change the qualified name of the classes and functions: https://github.com/python-trio/trio/blob/master/trio/__init__.py

Doing this results in `inspect.getsource(MyClass)` failing, which in turn means that `:member-order: bysource` fails in sphinx.

**Comment by letmaik** [comment]
Just a note for others, the following steps made it work automatically for me:
1. Copy [smart_resolver.py](https://github.com/astropy/sphinx-automodapi/blob/main/sphinx_automodapi/smart_resolver.py) in `doc/ext`.
2. In `conf.py`, add `sys.path.append(os.path.join(os.path.dirname(__file__), 'ext'))` and modify the extensions like so:
```py 
extensions = [
  ...,
  'sphinx.ext.intersphinx',
  'sphinx_autodoc_typehints',
  'smart_resolver'
  ]
```

**Comment by auscompgeek** [comment]
Instead of vendoring that module as suggested above, I would encourage people to pull in sphinx-automodapi as a dependency. No path hacks necessary.

**Comment by letmaik** [comment]
Good call, I wasn't aware that it supports smart_resolver to be consumed separately:
```py
extensions = [
...
'sphinx_automodapi.smart_resolver'
]
```

Shame that this isn't part of sphinx or some official sphinx extension.

**Comment by flying-sheep** [comment]
As of now, it is: sphinx-doc/sphinx#9026

**Comment by gaborbernat** [comment]
Resolved by the linked upstream change.
