### ISSUE TITLE
`typehints_defaults = "braces-after"` doesn't work correctly with multiline docstrings

### ISSUE THREAD

**Issue by KareemMAX** [tox-dev/sphinx-autodoc-typehints#384]
Currently we have this [docstring](https://github.com/unifyai/ivy/blob/main/ivy/data_classes/array/activations.py#L101-L116)
```
        Parameters
        ----------
        self
            input array.
        approximate
            whether to use the approximate version of the gelu function.
        complex_mode
            optional specifier for how to handle complex data types. See
            ``ivy.func_wrapper.handle_complex_input`` for more detail.
        out
            optional output array, for writing the result to. It must have a shape
            that the inputs broadcast to.
```

When we use `typehints_defaults = "braces-after"` it renders incorrectly for `complex_mode`:
<img width="698" alt="image" src="https://github.com/tox-dev/sphinx-autodoc-typehints/assets/16426366/60811a2d-3bd9-40cc-bdfe-9d2240ff00a5">

The `(default: 'jax')` should be places at the end of line 2 (after "more details."), while it's currently places after line 1 (See).

**Comment by gaborbernat** [comment]
PR welcome 👍
