### ISSUE TITLE
Support TypeVar arguments

### ISSUE THREAD

**Issue by gpkc** [tox-dev/sphinx-autodoc-typehints#39]
Example:

```python
class MyBase:
    """MyBase Doc"""

T = TypeVar('T', bound='MyBase')

class OtherClass:
    """OtherClass Doc"""
    def create_T(cls: Type[T]) -> T:
        """create_T Doc"""
        return cls()
```

This generates the following Warning:
`[...] OtherClass.create_T:: WARNING: py:class reference target not found: T`

**Comment by agronholm** [comment]
How are these supposed to be displayed?

**Comment by gpkc** [comment]
I'm not sure, really! Maybe in the case when the TypeVar is bound, you can assume that it is related to the bound class. In this case, objects of type `T` should be of a subclass of `MyBase` (or `MyBase` itself). How is this documented in languages that support polymorphism, such as C++?

**Comment by agronholm** [comment]
It's part of the type variable declaration in the class or method. I don't think I've ever seen a system like Python's anywhere so we're breaking new ground here.

**Comment by gpkc** [comment]
Yes, the system is a little different, but this is basically Python's generics (or templating) implementation. Maybe it could be similar to how other languages document generics as well.

**Comment by gpkc** [comment]
Just found this example: https://docs.oracle.com/javase/tutorial/java/generics/bounded.html

**Comment by agronholm** [comment]
I know how it looks like in Java. But that syntax is native to Java and is not just the way to document things. In Python I can't just do `repr()` on the type variable and get something presentable out. I'm also a bit unwilling to break new ground here by myself.

**Comment by gvanrossum** [comment]
If you want my feedback please point to some examples for how type annotations without generics are currently displayed.

**Comment by agronholm** [comment]
> If you want my feedback please point to some examples for how type annotations without generics are currently displayed.

You can find plenty of examples in [this project](http://asphalt.readthedocs.io/en/latest/py-modindex.html) (with and without generics) which uses sphinx-autodoc-typehints to generate the appropriate links.

**Comment by gvanrossum** [comment]
So the question is basically what to display instead of e.g. `T_Event` (which I see several times on [this page](http://asphalt.readthedocs.io/en/latest/modules/event.html#module-asphalt.core.event))? I'm not sure how much better you can do, though I'm not sure why sometimes a `~` appears in front of it. Maybe add an entry for `T_Event` itself (as if it were a class, say), at least if it's not trivial (say only if it has an upper bound or a value restriction).

FWIW I find the markup used for e.g. `Sequence[int]` or `Optional[str]` on that page really ugly -- it looks like e.g. `Optional` [ `str` ] which just make it way harder to parse visually than just plain `Optional[str]`.

**Comment by gpkc** [comment]
@gvanrossum The ~ is, according to the (sphinx reference)[http://www.sphinx-doc.org/en/stable/domains.html#cross-referencing-syntax]:

```
- If you prefix the content with ~, the link text will only be the last component of the target. For example, :py:meth:`~Queue.Queue.get` will refer to Queue.Queue.get but only display get as the link text.
```

So basically sphinx cannot find the reference to the given type, since it hasn't been processed accordingly.

**Comment by gpkc** [comment]
@gvanrossum Hehe, if you enter, say, `~Queue.Queue.get`, it will generate a link displayed as `get` instead of  `Queue.Queue.get`. It's just a detail.

**Comment by ilevkivskyi** [comment]
I think if you really want to support generics it would be necessary to add a separate line to docs saying something like:
```
This function/class is generic in ... <list of type variables (with variance for classes)>
```
Also for some inspiration this is how mypy itself renders a generic copy method:
```
def [T](self: T) -> T
```
As you understand, the `[T]` is important to indicate whether `T` is bound by the function/method or by the containing class.

**Comment by ilevkivskyi** [comment]
Also see potentially related issue on b.p.o. https://bugs.python.org/issue28519

**Comment by gpkc** [comment]
@ilevkivskyi Sorry, what do you mean by `mypy itself renders a generic copy method`? Where does mypy render this exactly? I don't recall this [T](...) syntax.
Btw I like your idea of adding a separate line. How do you think it should look like for the example I posted, where `T` is bound to `MyBase`?

**Comment by ilevkivskyi** [comment]
This form of representing callables appears in some error messages where callable is compared to callable, for example this code:
```python
from typing import Protocol, TypeVar

class A: ...
class B: ...
class C: ...

T = TypeVar('T', bound=C)
S = TypeVar('S', A, B)

class P(Protocol):
    def meth(self, arg: T) -> T:
        ...

class D:
    def meth(self, arg: S) -> S:
        ...

x: P = D()
```
generates this error:
```
test.py:18: error: Incompatible types in assignment (expression has type "D", variable has type "P")
test.py:18: note: Following member(s) of "D" have conflicts:
test.py:18: note:     Expected:
test.py:18: note:         def [T <: C] meth(self, arg: T) -> T
test.py:18: note:     Got:
test.py:18: note:         def [S in (A, B)] meth(self, arg: S) -> S
```
Concerning your example, the line should appear in the documentation for `create_T` (the class is not generic), it may be right after listing the arguments and return. The syntax for bound and value restrictions you see above. This is not specified by PEP 484 or any other docs, this is just a precedent of how these things are indicated in mypy.

**Comment by joelberkeley-pio** [comment]
I'd like to see a style [like scala's `@tparam`](https://docs.scala-lang.org/style/scaladoc.html), where the type var is documented at use site, not definition site. Something like
```python3
T = TypeVar('T')   # no docstring regardless of content

class Foo(Generic[T]):
    ```
    :tparam T: ...
    ```
    ...

**Comment by BvB93** [comment]
Would there be a simple way to just treat it them as aliases for `typing.TypeVar`?

**Comment by anselor** [comment]
I think this is the right place to post this. I ran into a problem with TypeVar's not getting resolved to anything, resulting in the py:class reference not found warning mentioned in the original post. Adding the type to the nitpick ignore list allowed me to generate documentation to be generated but resulted in no linkages to the type declaration. 

Doing the following got rid of the warning and also got all usages to link to link back to the attribute declaration.

I declare the TypeVar manually as an attribute in the rst file before the automodule call.

Using the example above:
```
class MyBase:
    """MyBase Doc"""

T = TypeVar('T', bound='MyBase')

class OtherClass:
    """OtherClass Doc"""
    def create_T(cls: Type[T]) -> T:
        """create_T Doc"""
        return cls()
```

Then in the module rst
```
.. py:attribute:: T
   :type: TypeVar
   :value: TypeVar('T', bound=MyBase)

Documentation about what T is goes here

.. automodule:: my.package
   :members:
   :undoc-members:
   :show-inheritance:

```

**Comment by hoefling** [comment]
We add a docstring to each `TypeVar` to get rid of the warnings for now:
```py
T = TypeVar('T', bound='MyBase')
"""
.. Note to devs: sphinx-autodoc can't document typevars properly right now,
   see https://github.com/agronholm/sphinx-autodoc-typehints/issues/39

A generic type representing this and that.
```
It can be crossreferenced via ``:py:data:`pkg.mod.T` `` throughout the docs.

**Comment by douglas-raillard-arm** [comment]
Unfortunately the trick of adding a docstring to the TypeVar fails in another case:
```
from typing import TypeVar

class Base:
    Nested = TypeVar('Nested')
    "nested typevar"

    def f(self) -> 'Base.Nested':
        "f hello"
        pass
```
This fails with:
```
docstring of module.Base.f:: WARNING: py:class reference target not found: module.Nested
```
Autodoc seems to fail seeing that the path to Nested is actually `module.Base.Nested`, not just `module.Nested`. Manually adding a `__qualname__` attribute does not seem to change anything. It's especially frustrating as replacing `TypeVar(...)` by anything else (e.g. `42`) works.

**Comment by gaborbernat** [comment]
We now switched to unrolling the type hint the same way we unroll Unions, Optionals, etc.
