### ISSUE TITLE
Wrap annotations with an html tag

### ISSUE THREAD

**Issue by pfebrer** [tox-dev/sphinx-autodoc-typehints#395]
Is it possible to wrap the annotation in some custom html tag?

I want to style the whole annotation to have the same background, but looking at the generated HTML it looks like an unnecessarily daunting task, with parenthesis and commas being just text and merged with the description text. This is `Union[str, int]`:
 
![Screenshot from 2023-11-03 14-16-03](https://github.com/tox-dev/sphinx-autodoc-typehints/assets/42074085/8d5f88f0-2b11-4c3b-819a-9d36a37bfc30)

which results in background changes for `[`, `]` and `,` making it very hard to read:

![Screenshot from 2023-11-03 14-18-36](https://github.com/tox-dev/sphinx-autodoc-typehints/assets/42074085/30dfc88f-a1aa-4dc4-9445-67d148e1d103)

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by pfebrer** [comment]
I would like to, but I don't know where to begin :sweat_smile:

**Comment by pfebrer** [comment]
Should I be able to acheive this with `typehints_formatter` ?

**Comment by hoodmane** [comment]
I did a similar thing in sphinx-js. It's largely a limitation of restructured text / the way that sphinx works. What I did is 
1. make a role which takes escaped rst, unescapes it, renders it into a docutils tree, and then wraps it with css span
https://github.com/pyodide/sphinx-js-fork/blob/master/sphinx_js/directives.py#L55-L66
2. when we render the type, escape your original rst and wrap it with the css anchor role:
https://github.com/pyodide/sphinx-js-fork/blob/master/sphinx_js/renderers.py#L432

I'm not sure if this is the best way, it feels a bit hacky but this was the best way I could figure out to make it work.

You can see the result here: all the types have this css wrapper. If you adjust the css for `.sphinx_js-type` you can add your box:
https://pyodide.org/en/latest/usage/api/js-api.html#pyodide

![Screenshot from 2023-11-03 11-51-48](https://github.com/tox-dev/sphinx-autodoc-typehints/assets/8739626/79d6cc77-b2e9-48a4-9799-c778b3423e3e)

**Comment by pfebrer** [comment]
Thanks for the comments! 

After some investigation I realized that as you point out I have to go too deep into sphinx to implement this and I think it's not worth it for me to spend time on. I thought it would be easier, I didn't know the inner workings of sphinx were so complicated 😅

**Comment by hoodmane** [comment]
I can try to do this when I get around to it. I think it's a very helpful feature.

**Comment by gaborbernat** [comment]
Agreed 👍

**Comment by pfebrer** [comment]
By the way I wonder if it would make more sense to contribute this to `sphinx.ext.autodoc`. I don't really know exactly what `sphinx.ext.autodoc` wants to support in terms of typehints, I'm new to this sphinx typehint world. But it seems that its support for typehints is quite good, no? Maybe it wasn't like this in the past (?)

**Comment by gaborbernat** [comment]
Their style of choice is different. Both packages can coexist.

**Comment by hoodmane** [comment]
Resolved by #397.
