### ISSUE TITLE
TypeVar broke with 1.25

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/sphinx-autodoc-typehints#398]
@hoodmane for some reason #397  broke tox documentation on TypeVar

<img width="416" alt="image" src="https://github.com/tox-dev/sphinx-autodoc-typehints/assets/690238/1e77d6a8-1825-4162-bc73-be835adad963">

https://github.com/tox-dev/tox/actions/runs/6822355429/job/18554265718

Any idea why is that?

_Originally posted by @gaborbernat in https://github.com/tox-dev/sphinx-autodoc-typehints/issues/397#issuecomment-1806076131_

**Comment by hoodmane** [comment]
I'll look into it. I guess the first step is to add a test case for this...

**Comment by hoodmane** [comment]
Most likely the problem is we need an extra backslash space somewhere.

**Comment by gaborbernat** [comment]
Thanks ❤️
