### ISSUE TITLE
`if TYPE_CHECKING` blocks not considered when resolving symbols

### ISSUE THREAD

**Issue by cjw296** [tox-dev/sphinx-autodoc-typehints#402]
I'm trying to use `sphinx-autodoc-typehints` to work around https://github.com/sphinx-doc/sphinx/issues/10785.

However, I need to use an `if TYPE_CHECKING` block to resolve an unavoidable circular import issue:

https://github.com/simplistix/sybil/blob/f6d8772a3f0b32c79a0b4cdd83d21098cb0721a7/sybil/typing.py#L1-L14

However, now I get:

```
WARNING: Cannot resolve forward reference in type annotations of "sybil.Sybil": name 'sybil' is not defined
```

...because it doesn't appear this package is considering imports within the `if TYPE_CHECKING`.

**Comment by hoodmane** [comment]
I think this is a duplicate of #22?

**Comment by cjw296** [comment]
Yep
