### ISSUE TITLE
Render union types using `|`

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/sphinx-autodoc-typehints#413]
Python [encourages](https://github.com/python/cpython/pull/30222) using `|` over `Union` and `Optional`. s-a-t should therefore render unions that way by default.

See [here](https://discuss.python.org/t/clarification-for-pep-604-is-foo-int-none-to-replace-all-use-of-foo-optional-int/26945/6) for more context.

Of note is the argument that `Optional` is actually misleading, since it implies something that doesn’t exist in Python:
- R has true support for optional parameters via `missing(param)`, which returns `TRUE` only when the function was called without specifying `param`.
- Contrast with Python, where `param: int | None = 4` is perfectly meaningful, while the same expressed as `param: Optional[int] = 4` is very confusing: The `Optional` seems to relate to the fact that the parameter can be left out when calling the function, but actually means that you can specify `param=None` to override the default of `4`. Weird!

**Comment by gboeing** [comment]
I am in total agreement with @flying-sheep. This would be a really great improvement.

**Comment by gaborbernat** [comment]
I'll review a PR if someone puts one in 👍 doing the change.

**Comment by gboeing** [comment]
Thanks @gaborbernat.

@flying-sheep are you open to creating a PR for what you proposed?

**Comment by flying-sheep** [comment]
I would, but #418 already exists. Also, I don‘t think it needs to be an option, it should just be how things are done, no?

**Comment by gboeing** [comment]
That was a quick PR! @flying-sheep I agree with you regarding the option... I'll leave a comment on the PR.
