### ISSUE TITLE
Type inspection fails if annotate with `type(TypeVar)`

### ISSUE THREAD

**Issue by Czaki** [tox-dev/sphinx-autodoc-typehints#417]
```python
EnumType = typing.TypeVar("EnumType", bound=Enum)


class EnumComboBox(QEnumComboBox):
    """
    Combobox for choose :py:class:`enum.Enum` values

    :param enum: Enum on which base combo box should be created.
        For proper showing labels overload the ``__str__`` function of given :py:class:`enum.Enum`
    """

    def __init__(self, enum: type(EnumType), parent=None):
```

Currently, sphinx-autodoc-typehints ails for cited code with exception: 

```
Handler <function process_docstring at 0x7fd2ced9ae80> for event 'autodoc-process-docstring' threw an exception (exception: type object 'TypeVar' has no attribute '__bound__')
```
After debug I found that exception is raised in line 222:

https://github.com/tox-dev/sphinx-autodoc-typehints/blob/a43776a1e636a0ae3c92764d65c0699ea46f8151/src/sphinx_autodoc_typehints/__init__.py#L221-L222

It looks like additional logic for handle `type(TypeVar(..., bound=)` needs to be added. 

Did I'm correct?

**Comment by hoodmane** [comment]
Is `type(EnumType)` a valid type annotation? It seems to me that it's the same as annotating it with `typing.TypeVar`. Do you really expect people to pass a typevar as the argument there?

**Comment by Czaki** [comment]
I want to people to pass Enum class, not Enum instance.

**Comment by hoodmane** [comment]
Isn't the correct thing `type[EnumType]`? 
https://docs.python.org/3/library/typing.html#the-type-of-class-objects

**Comment by hoodmane** [comment]
Or better yet `type[Enum]`?

**Comment by Czaki** [comment]
It looks like usage of `Type[EnumType]` works. 

It cannot be `Type[Enum]` as this type of annotation is used in annotating other methods, to know that it is always same enum.

So maybe this issue could be closed, and will be some source of knowledge, for someone else who meet same problem (as Google do not return any results for this message)
