### ISSUE TITLE
Also annotate parameter defaults.

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/sphinx-autodoc-typehints#48]
In numpy docstrings I often see

```rst
Parameters
----------
myparam : `Type`, optional (default: `None`)
    My param does things.
```

I prefer styling the parameter docs as definition list like numpydoc, where there is enough space for type and defaults:

<blockquote>
<dl>
<dt><strong>myparam</strong>: <code>Type</code>, optional (default: <code>None</code>)</dt>
<dd>My param does things.</dd>
</dl>
</blockquote>

However, the defaults get lost when migrating to sphinx-autodoc-typehints. I know the defaults are in the function signature above the param docs, but for long signatures (and therefor long lists of params), it would be best to also have them in the param docs.

Ideally we would parse and use the source code for the defaults instead of going from python objects back to strings, but using `repr` to get OK representations for most defaults would also be OK.

**Comment by flying-sheep** [comment]
The next release will add the following option:

> `document_defaults` (default: `None`): If `None`, defaults are not added. Otherwise adds a default annotation:
> 
>   - `'comma'` adds it after the type, changing Sphinx’ default look to “**param** (*int*, default: `1`) -- text”.
>   - `'braces'` adds `(default: ...)` after the type (useful for numpydoc like styles).
>   - `'braces-after'` adds `(default: ...)` at the end of the parameter documentation text instead.

@gaborbernat when are you planning to do a release? The last release broke [scanpydoc](https://github.com/theislab/scanpydoc), because it relied on a hack to make the defaults possible. If you release soon, I can fix scanpydoc by relying on this new feature.

**Comment by gaborbernat** [comment]
@flying-sheep https://github.com/tox-dev/sphinx-autodoc-typehints/actions/runs/1662682295

**Comment by flying-sheep** [comment]
wonderful, thank you!
