### ISSUE TITLE
Link to example Sphinx render leads to 404 Not Found

### ISSUE THREAD

**Issue by BrianJKoopman** [tox-dev/sphinx-autodoc-typehints#486]
This link at the top of your README points to a readthedocs page that results in a "404 Not Found" error:
https://github.com/tox-dev/sphinx-autodoc-typehints/blob/658bc809b4a8594e09ebbb9d699beec59ff956f4/README.md?plain=1#L11

It looks like it works if the `en/` is dropped, i.e. https://pyproject-api.readthedocs.io/latest/. Assuming this worked before I suspect something changed in your readthedocs config and it might need a redirect rule to fix the old link.

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/sphinx-autodoc-typehints/releases/tag/2.4.4
