### ISSUE TITLE
Wrong type using generics

### ISSUE THREAD

**Issue by thomasahle** [tox-dev/sphinx-autodoc-typehints#53]
I have a function with the following type:

```
X = TypeVar("X")
Y = TypeVar("Y")
Encoder = Callable[[], Callable[[X], Iterable[Y]]]

def run(encoder: Encoder[X, Y]) -> Iterable[Y]:
    ...
```

But when I run autodoc_typehints, it writes

```
Parameters: | encoder (Callable[[~X], ~Y]) – ...
Return type: |  (Nothing)
```

I would expect it to write the encoder type as either `Encoder[~X, ~Y]` or as ` Callable[[], Callable[[~X], Iterable[~Y]]]`.

**Comment by agronholm** [comment]
It can't be the first one because nothing will record the name of the variable you assigned the type alias into. As for the second, yeah, probably.

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
