### ISSUE TITLE
Mocked module not resolving correctly

### ISSUE THREAD

**Issue by willprice** [tox-dev/sphinx-autodoc-typehints#70]
Hello,
Thanks for the lovely library, it's super useful.

I seem to be having issues with the library when using `torch.Tensor` as a type annotation and mocking out the `torch` library. I can successfully use `PIL.Image.Image` as a type annotation (when mocking `PIL`).

If you have a look at the docs generated for [`PILVideotToTensor`](https://torchvideo.readthedocs.io/en/latest/transforms.html#torchvideo.transforms.PILVideoToTensor) you can see that `Image` is correctly resolved in the parameters of the function, however, the return type `torch.Tensor` is resolved as `<sphinx.ext.autodoc.importer._MockObject object at 0x7f44fa703a20>`.

Any ideas on what might be causing this? I've looked at the intersphinx objects.inv from the torch docs, and it `torch.Tensor` is listed as a class under the `:py:class` heading like `PIL.Image.Image` is in the Pillow objects.inv

**Comment by agronholm** [comment]
Why are you mocking libraries when generating the documentation in the first place?

**Comment by agronholm** [comment]
Answering my own question, I found this in your `conf.py`:
```
# Mock out all external dependencies as RTD fails to build otherwise -- sadly we've
# tried building with conda support but loading the conda-forge challenge uses up too
# much RAM and crashes the RTD worker
```
How do you expect sphinx-autodoc-typehints to figure out that it needs to point the link to a class that is not the actual target class it sees?

**Comment by agronholm** [comment]
Also, why would it be necessary to use Conda for building your docs? Aren't there wheels available for these dependencies?

**Comment by willprice** [comment]
All good questions.

> How do you expect sphinx-autodoc-typehints to figure out that it needs to point the link to a class that is not the actual target class it sees?

I'm not sure, but given that it can resolved the other mocked libraries like `PIL.Image.Image`, in the same way.

> Also, why would it be necessary to use Conda for building your docs? Aren't there wheels available for these dependencies?

Sadly not, I depend on some modules that have quite finicky dependencies that are only packaged on conda and not as wheels.

I'm not sure how sphinx-autodoc-typehints works under the hood, nor how the mocking in sphinx autodoc works, but for simple cases would a mock that sets the `__qualname__` as `self.__qualname__ + "." + name` on `__getattribute__(self, name)` not do the job?

**Comment by agronholm** [comment]
Well, turns out there are wheels but at least `torch` is prohibitively large (~600 MB) so mocking would be warranted indeed.

> I'm not sure how sphinx-autodoc-typehints works under the hood, nor how the mocking in sphinx autodoc works, but for simple cases would a mock that sets the __qualname__ as self.__qualname__ + "." + name on __getattribute__(self, name) not do the job?

I think it would, but doesn't look like the mocking library in use does that, given the results you're seeing.

**Comment by willprice** [comment]
Yeah the options were:

- Build with `requirements.txt`: Issue: `lintel` isn't packaged on PyPI (althought I could mock only that as it isn't present in type signatures). The dependencies are large and so installing them takes a lot of time/isn't very fair on the RTD people's servers.
- Build with conda: Issue: The dependencies are packaged on `conda-forge` which takes up too much RAM (RTD machines have 500MB, libraries that use conda-forge have to seek an exception, e.g. see the [xarray issue](https://github.com/pydata/xarray/issues/2209))
- Mock out all external dependencies: Issue: mucks up the types picked up by this library.

I still think mocking out the external dependencies is the best approach.

I've realised why the `PIL.Image.Image` is getting resolved; Pillow is being installed in the RTD virtualenv (https://readthedocs.org/projects/torchvideo/builds/8333442/) for some reason. Perhaps it's part of the default set of packages RTD install...

>I think it would, but doesn't look like the mocking library in use does that, given the results you're seeing.

Yes, now I understand that PIL *is* being imported and not mocked, I understand that `torch.Tensor` is the only thing that isn't installed and is present in the type signatures of the lib hence why the `Mock` reprs occur in the built documentation.

I'll have a look at building a mock that handles `__qualname__` correctly as currently [the built in `mock` library doesn't support it](https://bugs.python.org/issue32952). It's [quite easy to use custom mocks](https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules) instead of the autodoc mocking functionality.

I'm under the impression that a mock that correctly implements `__qualname__` should resolve the current issues I'm having and sphinx-autodoc-typehints will generate the correct sphinx directive, and from then on intersphinx should be able to resolve the class links. Do you agree, or have I misunderstood?

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
