### ISSUE TITLE
Return type appears only at very end of docstring

### ISSUE THREAD

**Issue by DataBranner** [tox-dev/sphinx-autodoc-typehints#75]
I find that the `Return type` is being added to the very end of the docstring, after other "discursive" content (containing prose discussion and Ipython directives that introduce example code). 

It seems to me that the `Return type` should appear before any discursive content, rather than after it.

I am using the following extensions:

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'IPython.sphinxext.ipython_directive',
    'IPython.sphinxext.ipython_console_highlighting',
    'sphinx.ext.napoleon',
    'sphinx_autodoc_typehints',                                                 
]
```
I don't see this issue mentioned in the Issues or the README. Is there a workaround?

**Comment by DataBranner** [comment]
Here is a minimal working example:

```
def temp(a: int) -> int:
    """
    First line of docstring text.

    Parameters
    ----------
    a
        Dummy text.


    Second line of docstring text.
    """
    return 0
```

In the rendered output the line

> **Return type**: `int`

appears after "Second line of docstring text." I think it is being tacked onto the end of the docstring, but that removes it from where it belongs logically. It should probably appear right after any parameters are listed.

Is there a way to specify where the "Return type" line gets populated in the docstring? If so, that would solve the problem. But I don't see mention of that in the README.

**Comment by agronholm** [comment]
The return type is placed after `:return:`, and in its absence, placed last, as there is no documented standard practice that says otherwise.

**Comment by gaborbernat** [comment]
Closing per above.
