### ISSUE TITLE
Format classes' bases

### ISSUE THREAD

**Issue by wheerd** [tox-dev/sphinx-autodoc-typehints#8]
I would like to have the extension also run the base classes through the annotation formatter, so that if I have some generic class, I can actually see the generic parameters in the documentation:

``` python
class MySpecialDict(Dict[str, int]):
    pass
```

Then in the docs it would render as:

``` rst
MySpecialDict
    Bases: :class:`~typing.Dict`\[:class:`str`, :class:`int`]
```

Then generic parameters of base classes would be visible and correctly linked.

This would require a new hook in the autodoc extension. I got some local code where this is already working. Since that requires changes to the autodoc extension, I wanted to check first if that is desired.

**Comment by agronholm** [comment]
Yes, I approve.

**Comment by wheerd** [comment]
Create an issue for the autodoc change: sphinx-doc/sphinx#3014

**Comment by agronholm** [comment]
Good luck with that. I have two pending, reviewed 1 or 2 line bugfix PRs with tests that have been collecting dust for 5 months.

**Comment by wheerd** [comment]
It is also possible to monkey patch that functionallity in by replacing `ClassDocumenter.add_directive_header`. I don't know if you are okay with a not so clean solution.
If you are, I can provide a pull request...

**Comment by agronholm** [comment]
If you want your issue to go anywhere within this decade, I suggest you make a PR against Sphinx.

**Comment by gaborbernat** [comment]
A PR for this would we welcome.

**Comment by gaborbernat** [comment]
Closing as did not see activity for a long time.
